### ISSUE TITLE
Move `showInCreationDialog` to `ui`

### ISSUE THREAD

**Issue by kdambekalns** [bwaidelich/Wwwision.Neos.CreationDialogProperties#1]
When looking at the example YAML, I stopped at `options.showInCreationDialog` and thought, "this is a UI option, so why not under `ui`…"

**Comment by bwaidelich** [comment]
because according to the yaml schema `options` is the extensible part while `ui` options are predefined AFAIK

**Comment by bwaidelich** [comment]
When this gets added to the core (which is currently being [discussed](https://discuss.neos.io/t/neos-4-3-lts-release-planning/3998)) we should definitely move it to `ui` and extend the schema accordingly
