### ISSUE TITLE
Package doesn't work in Neos UI 3.* and 2.*

### ISSUE THREAD

**Issue by petracoding** [bwaidelich/Wwwision.Neos.CreationDialogProperties#11]

**Comment by bwaidelich** [comment]
Thanks for reporting. Could you please add a description of what exactly is not working?

**Comment by jonnitto** [comment]
I've checked this with @petracoding, the bug where somewhere else. (I think there was an issue with the cache).

**Comment by bwaidelich** [comment]
Thanks for the update
